stages:
  - build
  - test
  - coverage-merge
  - sonarcloud
  - deploy

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .sonar/cache

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pip install coverage pytest
    - coverage run -m pytest tests/unit
    - pytest tests/unit --junitxml=junit.xml
    - mv .coverage .coverage.unit  # Renomeia para não sobrescrever
  artifacts:
    reports:
      junit: junit.xml
    paths:
      - .coverage.unit

integration-test-job:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pip install coverage pytest
    - coverage run -m pytest tests/integration
    - pytest tests/integration --junitxml=junit-integration.xml
    - mv .coverage .coverage.integration
  artifacts:
    reports:
      junit: junit-integration.xml
    paths:
      - .coverage.integration
  dependencies:
    - build-job

coverage-merge-job:
  stage: coverage-merge
  image: python:3.10
  dependencies:
    - unit-test-job
    - integration-test-job
  script:
    - pip install coverage
    - coverage combine .coverage.unit .coverage.integration
    - coverage xml
  artifacts:
    paths:
      - coverage.xml

sonarcloud-check:
  stage: sonarcloud
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - sonar-scanner \
      -Dsonar.projectKey=pedrohenriqueque-group_ExternoAPI \
      -Dsonar.organization=pedrohenriqueque-group \
      -Dsonar.sources=app \
      -Dsonar.python.version=3.10 \
      -Dsonar.python.coverage.reportPaths=coverage.xml \
      -Dsonar.sourceEncoding=UTF-8 \
      -Dsonar.login=$SONAR_TOKEN
  only:
    - merge_requests
    - master
    - develop
  dependencies:
    - coverage-merge-job

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
