stages:
  - build
  - test
  - sonarcloud
  - deploy

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"  # Necessário para Sonar identificar histórico
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .sonar/cache

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pip install coverage pytest
    - coverage run -m pytest tests/unit
    - pytest tests/unit --junitxml=junit.xml
  artifacts:
    reports:
      junit: junit.xml
    paths:
      - .coverage  # <-- importante salvar isso!
    expire_in: 1 hour

integration-test-job:
  stage: test
  image: python:3.10
  dependencies:
    - unit-test-job  # traz o .coverage
  script:
    - pip install -r requirements.txt
    - pip install coverage pytest
    - coverage run --append -m pytest tests/integration --junitxml=junit-integration.xml
    - coverage combine  # junta unit + integração
    - coverage xml       # gera coverage.xml final
  artifacts:
    reports:
      junit: junit-integration.xml
    paths:
      - .coverage
      - coverage.xml  # <- SonarCloud precisa disso
    expire_in: 1 hour

sonarcloud-check:
  stage: sonarcloud
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  dependencies:
    - integration-test-job  # precisa do coverage.xml final
  script:
    - sonar-scanner
      -Dsonar.projectKey=pedrohenriqueque-group_ExternoAPI
      -Dsonar.organization=pedrohenriqueque-group
      -Dsonar.sources=app
      -Dsonar.python.version=3.10
      -Dsonar.python.coverage.reportPaths=coverage.xml
      -Dsonar.sourceEncoding=UTF-8
      -Dsonar.login=$SONAR_TOKEN
  only:
    - merge_requests
    - master
    - develop

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
