stages:
  - build
  - test
  - sonarcloud
  - deploy

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  COVERAGE_FILE: ".coverage"  # força o mesmo arquivo coverage em todos os jobs

cache:
  paths:
    - .cache/pip
    - .sonar/cache

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - pip install coverage pytest
    - ls -la  # para depurar
    - coverage run -m pytest tests/unit
    - pytest tests/unit --junitxml=junit.xml
    - coverage xml
    - ls -la coverage.xml  # depuração
  artifacts:
    reports:
      junit: junit.xml
    paths:
      - .coverage
      - coverage.xml
    expire_in: 1 hour

integration-test-job:
  stage: test
  image: python:3.10
  dependencies:
    - unit-test-job  # garante que recebe .coverage do job anterior
  script:
    - pip install -r requirements.txt
    - pip install coverage pytest
    - ls -la  # verifica se .coverage veio do job anterior
    - coverage run --append -m pytest tests/integration --junitxml=junit-integration.xml
    - coverage combine  # combina os dados dos testes unitários + integração
    - coverage xml
    - ls -la coverage.xml  # depuração
  artifacts:
    reports:
      junit: junit-integration.xml
    paths:
      - .coverage
      - coverage.xml
    expire_in: 1 hour

sonarcloud-check:
  stage: sonarcloud
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - sonar-scanner
      -Dsonar.projectKey=pedrohenriqueque-group_ExternoAPI
      -Dsonar.organization=pedrohenriqueque-group
      -Dsonar.sources=app
      -Dsonar.python.version=3.10
      -Dsonar.python.coverage.reportPaths=coverage.xml
      -Dsonar.sourceEncoding=UTF-8
      -Dsonar.login=$SONAR_TOKEN
  only:
    - merge_requests
    - master
    - develop
  dependencies:
    - integration-test-job  # usa cobertura combinada

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
